name: Arduino Lint

on: [pull_request, push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove undistributed directories
        run: |
          rm -rf scripts tests
      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
