name: Compile Examples

on: [pull_request, push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          enable-warnings-report: true
      - uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: compile-sketches
          path: sketches-reports
          if-no-files-found: error
