name: Compile Examples

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            # Additional library dependencies can be listed here.
            # See: https://github.com/arduino/compile-sketches#libraries
          enable-warnings-report: true
      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: compilation-log
          path: sketches-reports
          if-no-files-found: error
