name: Compile Examples

on: [pull_request, push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile Sketches
        uses: arduino/compile-sketches@v1
        with:
          enable-warnings-report: true
      - name: Upload compilation results
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: compile-sketches
          path: sketches-reports
          if-no-files-found: error
